dist: bionic


language: python


python:
  - "3.7"


notifications:
  email: false


services:
  - docker


before_install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements-ml.txt
  - python3 -m pip install -r requirements.txt
  - docker build -t lml:latest .


install:
  - python3 ./setup.py install


script:
  python3 -m pytest -v src/main/python/tests
