dist: bionic
language: python
python:
  - "3.7"

notifications:
  email: false

services:
  - docker


before_install:
  - python3 -m pip install --quiet --upgrade pip
  - python3 -m pip install --quiet -r requirements-ml.txt
  - python3 -m pip install --quiet -r requirements.txt

install:
  - python3 ./setup.py install --quiet

script:
  python3 -m pytest -v src/main/python/tests


after_success:
  - export DEPLOY_TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
  # example: demo:20190405-171003-4-master
  # '/' is replaces by -
  - docker build -t open-prediction:${DEPLOY_TIMESTAMP}-${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH//[\/]/-} -t open-prediction:latest -f docker/Dockerfile .
  - scripts/ibm_image_registry.sh

# Needed to install IBM cloud cli
sudo: required

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/ibm_image_registry.sh
#    on:
#      branch: develop
