language: python
python:
  - "3.7"

# Additional services for testing and deployment
services:
  - docker

stages:
  - name: testing
  - name: deploy
    if: branch IN (master develop)

jobs:
  include:
    - stage: testing
      script: 
        - cd ml-service-implementations/ads-ml-service
        - pip3 install --quiet --upgrade pip
        - pip3 install --quiet -r requirements-test.txt
        - pip3 install --quiet -r requirements-ml.txt
        - pip3 install --quiet -r requirements.txt
        # Test project locally
        - python3 -m pytest -v app/tests
        # Test project inside container
        - docker run --rm -it --entrypoint="python3" ads-ml-service -m pytest /app/app/tests
    - script:
      - cd ml-service-implementations/wml-service
      - pip3 install --quiet tox
      - tox
    - script:
      - cd ml-service-implementations/sagemaker-service
      - pip3 install --quiet tox
      - tox
    - stage: deploy
      script: skip
      env: 
        - DEPLOY_TAG=$(date +'%Y%m%d-%H%M%S')-${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH//[\/]/-}
      deploy: 
        - provider: script
          script: ml-service-implementations/deploy.sh ads-ml-service
        - provider: script
          script: ml-service-implementations/deploy.sh wml-service
        - provider: script
          script: ml-service-implementations/deploy.sh sagemaker-service