language: python
python:
  - "3.7"

# Additional services for testing and deployment
services:
  - docker

stages:
  - name: testing
  - name: deploy
    if: branch IN (master, develop, release/2020Q3)

jobs:
  include:
    - stage: testing
      script:
        - cd ml-service-implementations/ads-ml-service
        - pip3 install --quiet --upgrade pip
        - pip3 install --quiet -r requirements-test.txt
        - pip3 install --quiet -r requirements-ml.txt
        - pip3 install --quiet -r requirements.txt
        - datamodel-codegen --input ../../open-prediction-service.yaml --input-file-type openapi --target-python-version 3.7 --output app/gen/schemas/ops_schemas.py
        - python3 -m pytest -v app/tests
      name: "ads-ml-service-test"
    - script:
      - cd ml-service-implementations/wml-service
      - pip3 install --quiet tox
      - tox
      name: "wml-proxy-test"
    - script:
      - cd ml-service-implementations/sagemaker-service
      - pip3 install --quiet tox
      - tox
      name: "sagemaker-proxy-test"
    - stage: deploy
      script: ml-service-implementations/deploy.sh ads-ml-service
      name: "ads-ml-service-deploy"
    -  script: ml-service-implementations/deploy.sh wml-service
       name: "wml-proxy-deploy"
    -  script: ml-service-implementations/deploy.sh sagemaker-service
       name: "sagemaker-proxy-deploy"