language: python
python:
  - "3.7"

# Additional services for testing and deployment
services:
  - docker

# Prepare pip for dependency installation
before_install:
  - python3 -m pip install --quiet --upgrade pip

# Install dependencies
install:
  - cd ml-service-implementations/ads-ml-service
  - python3 -m pip install --quiet -r requirements-test.txt
  - python3 -m pip install --quiet -r requirements-ml.txt
  - python3 -m pip install --quiet -r requirements.txt
  - export DEPLOY_TIMESTAMP=$(date +'%Y%m%d-%H%M')
  - docker build -t ads-ml-service:latest -f Dockerfile .
  # example tag: demo:20200729-1530-20-release-2020Q2
  - docker tag ads-ml-service:latest ads-ml-service:${DEPLOY_TIMESTAMP}-${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH//[\/]/-}

# Launch Testes
script:
  # Test project locally
  - python3 -m pytest -v app/tests
  # Test project inside container
  - docker run --rm -it --entrypoint="python3" ads-ml-service -m pytest /app/app/tests

# Needed to install IBM cloud cli
sudo: required

deploy:
  - provider: script
    script: chmod +x kubernetes/* && kubernetes/ibm_image_registry.sh
    on:
      all_branches: true
      condition: ${TRAVIS_BRANCH} == "release/${RELEASE_YEAR}${RELEASE_QUARTER}"
  - provider: script
    script: chmod +x kubernetes/* && kubernetes/docker_image_registry.sh
    on:
      all_branches: true
      condition: ${TRAVIS_BRANCH} == "release/${RELEASE_YEAR}${DESIGNER_COMPATIBLE_REL}"
