dist: bionic


language: python


python:
  - "3.7"


notifications:
  email: false


before_install:
  - pip install -r requirements.txt


install:
  - python ./setup.py install


script:
 python3 -m pytest -v src/main/python/tests


env:
  - model_storage=runtime/storage