dist: bionic


language: python


python:
  - "3.7"


notifications:
  email: false


services:
  - docker


before_install:
  - python3 -m pip install --quiet --upgrade pip
  - python3 -m pip install --quiet -r requirements-ml.txt
  - python3 -m pip install --quiet -r requirements.txt
  - docker build -t op:latest -f docker/Dockerfile .


install:
  - python3 ./setup.py install --quiet


script:
  python3 -m pytest -v src/main/python/tests
