dist: bionic


language: python


python:
  - "3.7"


notifications:
  email: false


services:
  - docker


before_install:
  - pip install -r requirements.txt        # dependencies for server test
  - pip install -r requirements-ml.txt     # dependencies for import and invocation test
  - docker build -t lml:latest .


install:
  - python ./setup.py install


script:
  python3 -m pytest -v src/main/python/tests
