name: sklearn-service
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=20.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - clickclick=20.10.2
  - connexion=2.7.0
  - cryptography=3.2.1
  - flask=1.1.2
  - idna=2.10
  - importlib_metadata=2.0.0
  - inflection=0.5.1
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - joblib=0.17.0
  - jsonschema=3.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - llvm-openmp=11.0.0
  - markupsafe=1.1.1
  - ncurses=6.2
  - numpy=1.19.4
  - openapi-spec-validator=0.2.9
  - openssl=1.1.1h
  - pathlib2=2.3.5
  - pip=20.2.4
  - pycparser=2.20
  - pyopenssl=20.0.0
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.25.0
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - swagger-ui-bundle=0.0.8
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tzdata
  - urllib3=1.25.11
  - werkzeug=1.0.1
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.0
  - zlib=1.2.11
