apiVersion: v1
kind: Service
metadata:
  name: ads-ml-service-service
  labels:
    app: open-prediction
spec:
  type: NodePort
  selector:
    app: open-prediction
  ports:
    - name: open-prediction-service-backend
      protocol: TCP
      port: 8080                         # Port that the ops actually expose. By default targetPort := port
      nodePort: 30000                    # External port of cluster
